/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGatePassRouteImport } from './routes/_authenticated/gate-pass'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIssuesRouteImport } from './routes/_authenticated/issues'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMedicalRouteImport } from './routes/_authenticated/medical'
import { Route as AuthenticatedMessRouteImport } from './routes/_authenticated/mess'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches.index'
import { Route as AuthenticatedHostelsIndexRouteImport } from './routes/_authenticated/hostels.index'
import { Route as AuthenticatedHostelsHostelIdRouteImport } from './routes/_authenticated/hostels.$hostelId'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGatePassRoute = AuthenticatedGatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIssuesRoute = AuthenticatedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicalRoute = AuthenticatedMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessRoute = AuthenticatedMessRouteImport.update({
  id: '/mess',
  path: '/mess',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBranchesRoute,
  } as any)
const AuthenticatedHostelsIndexRoute =
  AuthenticatedHostelsIndexRouteImport.update({
    id: '/hostels/',
    path: '/hostels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostelsHostelIdRoute =
  AuthenticatedHostelsHostelIdRouteImport.update({
    id: '/hostels/$hostelId',
    path: '/hostels/$hostelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRouteWithChildren
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gate-pass': typeof AuthenticatedGatePassRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/mess': typeof AuthenticatedMessRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/hostels/$hostelId': typeof AuthenticatedHostelsHostelIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/branches/': typeof AuthenticatedBranchesIndexRoute
  '/hostels/': typeof AuthenticatedHostelsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gate-pass': typeof AuthenticatedGatePassRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/mess': typeof AuthenticatedMessRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/hostels/$hostelId': typeof AuthenticatedHostelsHostelIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/hostels': typeof AuthenticatedHostelsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRouteWithChildren
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/gate-pass': typeof AuthenticatedGatePassRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/issues': typeof AuthenticatedIssuesRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/medical': typeof AuthenticatedMedicalRoute
  '/_authenticated/mess': typeof AuthenticatedMessRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
  '/_authenticated/hostels/$hostelId': typeof AuthenticatedHostelsHostelIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/hostels/': typeof AuthenticatedHostelsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admissions'
    | '/ai-settings'
    | '/assets'
    | '/assistant'
    | '/attendance'
    | '/audit'
    | '/branches'
    | '/complaints'
    | '/dashboard'
    | '/donations'
    | '/expenses'
    | '/finance'
    | '/gate-pass'
    | '/inventory'
    | '/issues'
    | '/leave'
    | '/maintenance'
    | '/medical'
    | '/mess'
    | '/notifications'
    | '/reports'
    | '/security'
    | '/settings'
    | '/staff'
    | '/team'
    | '/trust'
    | '/visitors'
    | '/hostels/$hostelId'
    | '/students/$studentId'
    | '/branches/'
    | '/hostels/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admissions'
    | '/ai-settings'
    | '/assets'
    | '/assistant'
    | '/attendance'
    | '/audit'
    | '/complaints'
    | '/dashboard'
    | '/donations'
    | '/expenses'
    | '/finance'
    | '/gate-pass'
    | '/inventory'
    | '/issues'
    | '/leave'
    | '/maintenance'
    | '/medical'
    | '/mess'
    | '/notifications'
    | '/reports'
    | '/security'
    | '/settings'
    | '/staff'
    | '/team'
    | '/trust'
    | '/visitors'
    | '/hostels/$hostelId'
    | '/students/$studentId'
    | '/branches'
    | '/hostels'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admissions'
    | '/_authenticated/ai-settings'
    | '/_authenticated/assets'
    | '/_authenticated/assistant'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/branches'
    | '/_authenticated/complaints'
    | '/_authenticated/dashboard'
    | '/_authenticated/donations'
    | '/_authenticated/expenses'
    | '/_authenticated/finance'
    | '/_authenticated/gate-pass'
    | '/_authenticated/inventory'
    | '/_authenticated/issues'
    | '/_authenticated/leave'
    | '/_authenticated/maintenance'
    | '/_authenticated/medical'
    | '/_authenticated/mess'
    | '/_authenticated/notifications'
    | '/_authenticated/reports'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/team'
    | '/_authenticated/trust'
    | '/_authenticated/visitors'
    | '/_authenticated/hostels/$hostelId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/branches/'
    | '/_authenticated/hostels/'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate-pass': {
      id: '/_authenticated/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof AuthenticatedGatePassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issues': {
      id: '/_authenticated/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AuthenticatedIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical': {
      id: '/_authenticated/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof AuthenticatedMedicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mess': {
      id: '/_authenticated/mess'
      path: '/mess'
      fullPath: '/mess'
      preLoaderRoute: typeof AuthenticatedMessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedBranchesRoute
    }
    '/_authenticated/hostels/': {
      id: '/_authenticated/hostels/'
      path: '/hostels'
      fullPath: '/hostels/'
      preLoaderRoute: typeof AuthenticatedHostelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hostels/$hostelId': {
      id: '/_authenticated/hostels/$hostelId'
      path: '/hostels/$hostelId'
      fullPath: '/hostels/$hostelId'
      preLoaderRoute: typeof AuthenticatedHostelsHostelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBranchesRouteChildren {
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
}

const AuthenticatedBranchesRouteChildren: AuthenticatedBranchesRouteChildren = {
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
}

const AuthenticatedBranchesRouteWithChildren =
  AuthenticatedBranchesRoute._addFileChildren(
    AuthenticatedBranchesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRouteWithChildren
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGatePassRoute: typeof AuthenticatedGatePassRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedIssuesRoute: typeof AuthenticatedIssuesRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMedicalRoute: typeof AuthenticatedMedicalRoute
  AuthenticatedMessRoute: typeof AuthenticatedMessRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRoute
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
  AuthenticatedHostelsHostelIdRoute: typeof AuthenticatedHostelsHostelIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedHostelsIndexRoute: typeof AuthenticatedHostelsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRouteWithChildren,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGatePassRoute: AuthenticatedGatePassRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedIssuesRoute: AuthenticatedIssuesRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMedicalRoute: AuthenticatedMedicalRoute,
  AuthenticatedMessRoute: AuthenticatedMessRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRoute,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
  AuthenticatedHostelsHostelIdRoute: AuthenticatedHostelsHostelIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedHostelsIndexRoute: AuthenticatedHostelsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
