/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporatePartnershipRouteImport } from './routes/corporate-partnership'
import { Route as DhyanaYogaRouteImport } from './routes/dhyana-yoga'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EducationRouteImport } from './routes/education'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequestHelpRouteImport } from './routes/request-help'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as VolunteerRegistrationRouteImport } from './routes/volunteer-registration'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAchievementsRouteImport } from './routes/about.achievements'
import { Route as AboutJourneyRouteImport } from './routes/about.journey'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutSvrstTrustRouteImport } from './routes/about.svrst-trust'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsGalleryRouteImport } from './routes/events.gallery'
import { Route as EventsPastRouteImport } from './routes/events.past'
import { Route as EventsRegisterRouteImport } from './routes/events.register'
import { Route as EventsUpcomingRouteImport } from './routes/events.upcoming'
import { Route as GetInvolvedIndexRouteImport } from './routes/get-involved.index'
import { Route as GetInvolvedMembershipRouteImport } from './routes/get-involved.membership'
import { Route as PoliciesDonationRouteImport } from './routes/policies.donation'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePartnershipRoute = CorporatePartnershipRouteImport.update({
  id: '/corporate-partnership',
  path: '/corporate-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const DhyanaYogaRoute = DhyanaYogaRouteImport.update({
  id: '/dhyana-yoga',
  path: '/dhyana-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestHelpRoute = RequestHelpRouteImport.update({
  id: '/request-help',
  path: '/request-help',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRegistrationRoute = VolunteerRegistrationRouteImport.update({
  id: '/volunteer-registration',
  path: '/volunteer-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAchievementsRoute = AboutAchievementsRouteImport.update({
  id: '/about/achievements',
  path: '/about/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutJourneyRoute = AboutJourneyRouteImport.update({
  id: '/about/journey',
  path: '/about/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSvrstTrustRoute = AboutSvrstTrustRouteImport.update({
  id: '/about/svrst-trust',
  path: '/about/svrst-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsGalleryRoute = EventsGalleryRouteImport.update({
  id: '/events/gallery',
  path: '/events/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPastRoute = EventsPastRouteImport.update({
  id: '/events/past',
  path: '/events/past',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRegisterRoute = EventsRegisterRouteImport.update({
  id: '/events/register',
  path: '/events/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsUpcomingRoute = EventsUpcomingRouteImport.update({
  id: '/events/upcoming',
  path: '/events/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedIndexRoute = GetInvolvedIndexRouteImport.update({
  id: '/get-involved/',
  path: '/get-involved/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedMembershipRoute = GetInvolvedMembershipRouteImport.update({
  id: '/get-involved/membership',
  path: '/get-involved/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesDonationRoute = PoliciesDonationRouteImport.update({
  id: '/policies/donation',
  path: '/policies/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate-partnership': typeof CorporatePartnershipRoute
  '/dhyana-yoga': typeof DhyanaYogaRoute
  '/donate': typeof DonateRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/request-help': typeof RequestHelpRoute
  '/sports': typeof SportsRoute
  '/volunteer-registration': typeof VolunteerRegistrationRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/past': typeof EventsPastRoute
  '/events/register': typeof EventsRegisterRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/policies/donation': typeof PoliciesDonationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate-partnership': typeof CorporatePartnershipRoute
  '/dhyana-yoga': typeof DhyanaYogaRoute
  '/donate': typeof DonateRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/request-help': typeof RequestHelpRoute
  '/sports': typeof SportsRoute
  '/volunteer-registration': typeof VolunteerRegistrationRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/past': typeof EventsPastRoute
  '/events/register': typeof EventsRegisterRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/policies/donation': typeof PoliciesDonationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about': typeof AboutIndexRoute
  '/events': typeof EventsIndexRoute
  '/get-involved': typeof GetInvolvedIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate-partnership': typeof CorporatePartnershipRoute
  '/dhyana-yoga': typeof DhyanaYogaRoute
  '/donate': typeof DonateRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/request-help': typeof RequestHelpRoute
  '/sports': typeof SportsRoute
  '/volunteer-registration': typeof VolunteerRegistrationRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/past': typeof EventsPastRoute
  '/events/register': typeof EventsRegisterRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/policies/donation': typeof PoliciesDonationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/corporate-partnership'
    | '/dhyana-yoga'
    | '/donate'
    | '/education'
    | '/login'
    | '/request-help'
    | '/sports'
    | '/volunteer-registration'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/events/gallery'
    | '/events/past'
    | '/events/register'
    | '/events/upcoming'
    | '/get-involved/membership'
    | '/policies/donation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/work/$slug'
    | '/about/'
    | '/events/'
    | '/get-involved/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/corporate-partnership'
    | '/dhyana-yoga'
    | '/donate'
    | '/education'
    | '/login'
    | '/request-help'
    | '/sports'
    | '/volunteer-registration'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/events/gallery'
    | '/events/past'
    | '/events/register'
    | '/events/upcoming'
    | '/get-involved/membership'
    | '/policies/donation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/work/$slug'
    | '/about'
    | '/events'
    | '/get-involved'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/corporate-partnership'
    | '/dhyana-yoga'
    | '/donate'
    | '/education'
    | '/login'
    | '/request-help'
    | '/sports'
    | '/volunteer-registration'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/events/gallery'
    | '/events/past'
    | '/events/register'
    | '/events/upcoming'
    | '/get-involved/membership'
    | '/policies/donation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/work/$slug'
    | '/about/'
    | '/events/'
    | '/get-involved/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CorporatePartnershipRoute: typeof CorporatePartnershipRoute
  DhyanaYogaRoute: typeof DhyanaYogaRoute
  DonateRoute: typeof DonateRoute
  EducationRoute: typeof EducationRoute
  LoginRoute: typeof LoginRoute
  RequestHelpRoute: typeof RequestHelpRoute
  SportsRoute: typeof SportsRoute
  VolunteerRegistrationRoute: typeof VolunteerRegistrationRoute
  AboutAchievementsRoute: typeof AboutAchievementsRoute
  AboutJourneyRoute: typeof AboutJourneyRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutSvrstTrustRoute: typeof AboutSvrstTrustRoute
  EventsGalleryRoute: typeof EventsGalleryRoute
  EventsPastRoute: typeof EventsPastRoute
  EventsRegisterRoute: typeof EventsRegisterRoute
  EventsUpcomingRoute: typeof EventsUpcomingRoute
  GetInvolvedMembershipRoute: typeof GetInvolvedMembershipRoute
  PoliciesDonationRoute: typeof PoliciesDonationRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GetInvolvedIndexRoute: typeof GetInvolvedIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-partnership': {
      id: '/corporate-partnership'
      path: '/corporate-partnership'
      fullPath: '/corporate-partnership'
      preLoaderRoute: typeof CorporatePartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhyana-yoga': {
      id: '/dhyana-yoga'
      path: '/dhyana-yoga'
      fullPath: '/dhyana-yoga'
      preLoaderRoute: typeof DhyanaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-help': {
      id: '/request-help'
      path: '/request-help'
      fullPath: '/request-help'
      preLoaderRoute: typeof RequestHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-registration': {
      id: '/volunteer-registration'
      path: '/volunteer-registration'
      fullPath: '/volunteer-registration'
      preLoaderRoute: typeof VolunteerRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/achievements': {
      id: '/about/achievements'
      path: '/about/achievements'
      fullPath: '/about/achievements'
      preLoaderRoute: typeof AboutAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/journey': {
      id: '/about/journey'
      path: '/about/journey'
      fullPath: '/about/journey'
      preLoaderRoute: typeof AboutJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/svrst-trust': {
      id: '/about/svrst-trust'
      path: '/about/svrst-trust'
      fullPath: '/about/svrst-trust'
      preLoaderRoute: typeof AboutSvrstTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/gallery': {
      id: '/events/gallery'
      path: '/events/gallery'
      fullPath: '/events/gallery'
      preLoaderRoute: typeof EventsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/past': {
      id: '/events/past'
      path: '/events/past'
      fullPath: '/events/past'
      preLoaderRoute: typeof EventsPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/register': {
      id: '/events/register'
      path: '/events/register'
      fullPath: '/events/register'
      preLoaderRoute: typeof EventsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/upcoming': {
      id: '/events/upcoming'
      path: '/events/upcoming'
      fullPath: '/events/upcoming'
      preLoaderRoute: typeof EventsUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/': {
      id: '/get-involved/'
      path: '/get-involved'
      fullPath: '/get-involved/'
      preLoaderRoute: typeof GetInvolvedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/membership': {
      id: '/get-involved/membership'
      path: '/get-involved/membership'
      fullPath: '/get-involved/membership'
      preLoaderRoute: typeof GetInvolvedMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/donation': {
      id: '/policies/donation'
      path: '/policies/donation'
      fullPath: '/policies/donation'
      preLoaderRoute: typeof PoliciesDonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CorporatePartnershipRoute: CorporatePartnershipRoute,
  DhyanaYogaRoute: DhyanaYogaRoute,
  DonateRoute: DonateRoute,
  EducationRoute: EducationRoute,
  LoginRoute: LoginRoute,
  RequestHelpRoute: RequestHelpRoute,
  SportsRoute: SportsRoute,
  VolunteerRegistrationRoute: VolunteerRegistrationRoute,
  AboutAchievementsRoute: AboutAchievementsRoute,
  AboutJourneyRoute: AboutJourneyRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutSvrstTrustRoute: AboutSvrstTrustRoute,
  EventsGalleryRoute: EventsGalleryRoute,
  EventsPastRoute: EventsPastRoute,
  EventsRegisterRoute: EventsRegisterRoute,
  EventsUpcomingRoute: EventsUpcomingRoute,
  GetInvolvedMembershipRoute: GetInvolvedMembershipRoute,
  PoliciesDonationRoute: PoliciesDonationRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  WorkSlugRoute: WorkSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GetInvolvedIndexRoute: GetInvolvedIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
