/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAchievementsRouteImport } from './routes/about.achievements'
import { Route as AboutJourneyRouteImport } from './routes/about.journey'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutSvrstTrustRouteImport } from './routes/about.svrst-trust'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsPastRouteImport } from './routes/events.past'
import { Route as EventsUpcomingRouteImport } from './routes/events.upcoming'
import { Route as GetInvolvedIndexRouteImport } from './routes/get-involved.index'
import { Route as GetInvolvedCorporatePartnershipRouteImport } from './routes/get-involved.corporate-partnership'
import { Route as GetInvolvedMembershipRouteImport } from './routes/get-involved.membership'
import { Route as GetInvolvedRequestHelpRouteImport } from './routes/get-involved.request-help'
import { Route as GetInvolvedVolunteerRouteImport } from './routes/get-involved.volunteer'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAchievementsRoute = AboutAchievementsRouteImport.update({
  id: '/about/achievements',
  path: '/about/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutJourneyRoute = AboutJourneyRouteImport.update({
  id: '/about/journey',
  path: '/about/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSvrstTrustRoute = AboutSvrstTrustRouteImport.update({
  id: '/about/svrst-trust',
  path: '/about/svrst-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPastRoute = EventsPastRouteImport.update({
  id: '/events/past',
  path: '/events/past',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsUpcomingRoute = EventsUpcomingRouteImport.update({
  id: '/events/upcoming',
  path: '/events/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedIndexRoute = GetInvolvedIndexRouteImport.update({
  id: '/get-involved/',
  path: '/get-involved/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedCorporatePartnershipRoute =
  GetInvolvedCorporatePartnershipRouteImport.update({
    id: '/get-involved/corporate-partnership',
    path: '/get-involved/corporate-partnership',
    getParentRoute: () => rootRouteImport,
  } as any)
const GetInvolvedMembershipRoute = GetInvolvedMembershipRouteImport.update({
  id: '/get-involved/membership',
  path: '/get-involved/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRequestHelpRoute = GetInvolvedRequestHelpRouteImport.update({
  id: '/get-involved/request-help',
  path: '/get-involved/request-help',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedVolunteerRoute = GetInvolvedVolunteerRouteImport.update({
  id: '/get-involved/volunteer',
  path: '/get-involved/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/about/team': typeof AboutTeamRoute
  '/events/past': typeof EventsPastRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/corporate-partnership': typeof GetInvolvedCorporatePartnershipRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/get-involved/request-help': typeof GetInvolvedRequestHelpRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/about/team': typeof AboutTeamRoute
  '/events/past': typeof EventsPastRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/corporate-partnership': typeof GetInvolvedCorporatePartnershipRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/get-involved/request-help': typeof GetInvolvedRequestHelpRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about': typeof AboutIndexRoute
  '/events': typeof EventsIndexRoute
  '/get-involved': typeof GetInvolvedIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/achievements': typeof AboutAchievementsRoute
  '/about/journey': typeof AboutJourneyRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/svrst-trust': typeof AboutSvrstTrustRoute
  '/about/team': typeof AboutTeamRoute
  '/events/past': typeof EventsPastRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/get-involved/corporate-partnership': typeof GetInvolvedCorporatePartnershipRoute
  '/get-involved/membership': typeof GetInvolvedMembershipRoute
  '/get-involved/request-help': typeof GetInvolvedRequestHelpRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/about/team'
    | '/events/past'
    | '/events/upcoming'
    | '/get-involved/corporate-partnership'
    | '/get-involved/membership'
    | '/get-involved/request-help'
    | '/get-involved/volunteer'
    | '/work/$slug'
    | '/about/'
    | '/events/'
    | '/get-involved/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/about/team'
    | '/events/past'
    | '/events/upcoming'
    | '/get-involved/corporate-partnership'
    | '/get-involved/membership'
    | '/get-involved/request-help'
    | '/get-involved/volunteer'
    | '/work/$slug'
    | '/about'
    | '/events'
    | '/get-involved'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about/achievements'
    | '/about/journey'
    | '/about/mission'
    | '/about/svrst-trust'
    | '/about/team'
    | '/events/past'
    | '/events/upcoming'
    | '/get-involved/corporate-partnership'
    | '/get-involved/membership'
    | '/get-involved/request-help'
    | '/get-involved/volunteer'
    | '/work/$slug'
    | '/about/'
    | '/events/'
    | '/get-involved/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAchievementsRoute: typeof AboutAchievementsRoute
  AboutJourneyRoute: typeof AboutJourneyRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutSvrstTrustRoute: typeof AboutSvrstTrustRoute
  AboutTeamRoute: typeof AboutTeamRoute
  EventsPastRoute: typeof EventsPastRoute
  EventsUpcomingRoute: typeof EventsUpcomingRoute
  GetInvolvedCorporatePartnershipRoute: typeof GetInvolvedCorporatePartnershipRoute
  GetInvolvedMembershipRoute: typeof GetInvolvedMembershipRoute
  GetInvolvedRequestHelpRoute: typeof GetInvolvedRequestHelpRoute
  GetInvolvedVolunteerRoute: typeof GetInvolvedVolunteerRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GetInvolvedIndexRoute: typeof GetInvolvedIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/achievements': {
      id: '/about/achievements'
      path: '/about/achievements'
      fullPath: '/about/achievements'
      preLoaderRoute: typeof AboutAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/journey': {
      id: '/about/journey'
      path: '/about/journey'
      fullPath: '/about/journey'
      preLoaderRoute: typeof AboutJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/svrst-trust': {
      id: '/about/svrst-trust'
      path: '/about/svrst-trust'
      fullPath: '/about/svrst-trust'
      preLoaderRoute: typeof AboutSvrstTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/past': {
      id: '/events/past'
      path: '/events/past'
      fullPath: '/events/past'
      preLoaderRoute: typeof EventsPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/upcoming': {
      id: '/events/upcoming'
      path: '/events/upcoming'
      fullPath: '/events/upcoming'
      preLoaderRoute: typeof EventsUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/': {
      id: '/get-involved/'
      path: '/get-involved'
      fullPath: '/get-involved/'
      preLoaderRoute: typeof GetInvolvedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/corporate-partnership': {
      id: '/get-involved/corporate-partnership'
      path: '/get-involved/corporate-partnership'
      fullPath: '/get-involved/corporate-partnership'
      preLoaderRoute: typeof GetInvolvedCorporatePartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/membership': {
      id: '/get-involved/membership'
      path: '/get-involved/membership'
      fullPath: '/get-involved/membership'
      preLoaderRoute: typeof GetInvolvedMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/request-help': {
      id: '/get-involved/request-help'
      path: '/get-involved/request-help'
      fullPath: '/get-involved/request-help'
      preLoaderRoute: typeof GetInvolvedRequestHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/volunteer': {
      id: '/get-involved/volunteer'
      path: '/get-involved/volunteer'
      fullPath: '/get-involved/volunteer'
      preLoaderRoute: typeof GetInvolvedVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAchievementsRoute: AboutAchievementsRoute,
  AboutJourneyRoute: AboutJourneyRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutSvrstTrustRoute: AboutSvrstTrustRoute,
  AboutTeamRoute: AboutTeamRoute,
  EventsPastRoute: EventsPastRoute,
  EventsUpcomingRoute: EventsUpcomingRoute,
  GetInvolvedCorporatePartnershipRoute: GetInvolvedCorporatePartnershipRoute,
  GetInvolvedMembershipRoute: GetInvolvedMembershipRoute,
  GetInvolvedRequestHelpRoute: GetInvolvedRequestHelpRoute,
  GetInvolvedVolunteerRoute: GetInvolvedVolunteerRoute,
  WorkSlugRoute: WorkSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GetInvolvedIndexRoute: GetInvolvedIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
